### ISSUE TITLE
Modelo de datos de Usuaio

### ISSUE THREAD

**Issue by leoachear** [frontendcafe/cmyk-mango#117]
- Revisar las pantallas de la app para determinar el modelo de los datos del usuario (¿Qué campos son necesarios?).

- Armarlo en formato Json

- Hay armado un modelo de datos, pero solo tiene datos de la reunión.

**Comment by DamianPalavecino** [comment]
https://drive.google.com/file/d/11W9DoRXnMn2U_I7hvFsVWXsZw7I9Qx86/view?usp=sharing
