### ISSUE TITLE
Página nueva reunión: paso 4 - invitación

### ISSUE THREAD

**Issue by MatiasOlivera** [frontendcafe/cmyk-mango#18]
Cómo un usuario, quiero compartir el link de Mango o enviar un email para invitar a las personas a unirse a la reunión.

### Desktop
![nueva-reunion-invitacion](https://user-images.githubusercontent.com/16739011/132110379-0ad5d5cf-d913-4a1e-b306-92278d4d9112.png)

### Mobile
![nueva-reunion-invitacion-mobile](https://user-images.githubusercontent.com/16739011/132110381-4995f23c-42b9-4bc4-932f-995c096e12cf.png)

**Comment by lucianina1994** [comment]
@MatiasOlivera hola otra vez, voy a tomar esta al final!
