### ISSUE TITLE
Página votación

### ISSUE THREAD

**Issue by MatiasOlivera** [frontendcafe/cmyk-mango#21]
Cómo un usuario, quiero votar un horario para que en lo posible la reunión se haga en un horario que me quede cómodo.

### Desktop
![votacion](https://user-images.githubusercontent.com/16739011/132111089-dbf011d0-91bb-43a3-8520-49bd058bda5f.png)

### Mobile
![votacion-mobile](https://user-images.githubusercontent.com/16739011/132111090-a7954684-ef5c-4877-b451-684cb24c7e2b.png)

**Comment by lucianina1994** [comment]
@MatiasOlivera Buenas, proximamente puedo tomar esta issue?

**Comment by MatiasOlivera** [comment]
@lucianina1994 Sí, podes tomarla
