### ISSUE TITLE
Endpoint registro

### ISSUE THREAD

**Issue by MatiasOlivera** [frontendcafe/cmyk-mango#3]
Cómo un usuario, quiero crear una cuenta para usar la aplicación.

Ruta: `/registro`
Método: `POST`
Payload:
 - nombre: string
 - email: string
 - password: string
 - ciudad: string

Ejemplo:
```
{
  "nombre": "Juan Perez",
  "email": "juanperez@email.com",
  "password": "password1234",
  "ciudad": "Buenos Aires, Argentina"
}
```

**Comment by leoachear** [comment]
@MatiasOlivera ¿Se pueden agarrar estas tareas de Backend?
