### ISSUE TITLE
Componente AuthLayout

### ISSUE THREAD

**Issue by MatiasOlivera** [frontendcafe/cmyk-mango#87]
Desktop
![inicio-layout](https://user-images.githubusercontent.com/16739011/132109557-92e6d924-875d-45cc-817d-9edcc8754be1.png)

Mobile:
![inicio-layout-mobile](https://user-images.githubusercontent.com/16739011/132109913-b63f065b-1f2e-4a5c-afa4-386ed5503caf.png)

**Comment by leoachear** [comment]
@MatiasOlivera la parte de Mobile debería ser sin el menu y sin la campanita de notificaciones porque sería para cuando el usuario no está logueado ¿no?

Lo otro que me genera dudas es que en el diseño de figma, hay dos versiones que debería manejar este componente para la vista mobile ¿no? 🤔

![image](https://user-images.githubusercontent.com/7539443/140991085-6e748298-8f77-4d69-9035-24a3c205f87d.png)
